name: lint 👅

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: lint
        run: |
          npm install
          npm run lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: test
        id: build
        run: |
          npm install
          npm run test
